### ISSUE TITLE
Experiment with the resource system

### ISSUE THREAD

**Issue by paulcscharf** [beardgame/td#10]
- [ ] Should we keep the fluid thing?
- [ ] Should resources come from enemy kills instead?

**Comment by paulcscharf** [comment]
I'm open to making things less fluid (though we don't really need to change the system for that I figure). But I do like the building queue a lot as well. And the current system allows for that very trivially.

**Comment by paulcscharf** [comment]
Elegantly even.

**Comment by tomrijnbeek** [comment]
Added some flexibility through constants to play around with resources. Gave it a first try in the branch started by 5b223df.

**Comment by tomrijnbeek** [comment]
Technologies now get more expensive after each technology you unlock. This will make it a bit harder to _just_ get all technologies towards the end of the game.
